version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: pingbadge_user
      POSTGRES_PASSWORD: pingbadge_password
      POSTGRES_DB: pingbadge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pingbadge_user -d pingbadge_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  api:
    build: .
    environment:
      DATABASE_URL: postgres://pingbadge_user:pingbadge_password@postgres:5432/pingbadge_db?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 8080
      GIN_MODE: release
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
